### ISSUE TITLE
Change MOSART runoff model in compset?

### ISSUE THREAD

**Issue by evalieungh** [NorESMhub/NorESM_LandSites_Platform#105]
@mvdebolskiy mentioned we might want to change the compset for default cases away from MOSART and rather use stub (?) runoff if we want to make it easier to add new sites. 

If I remember correctly, @huitang-earth chose the compset with MOSART long ago and no-one has changed it afterwards. Is there a reason to keep MOSART as default?

A solution might be to change the default to the stub runoff, but add an option for changing to MOSART when we add possibility for users to modify case compsets. @ka7eh, what do you think about compset customisation?

**Comment by ka7eh** [comment]
Making compsets customizable should be straightforward. I think the main change would be in configs, where we define what predefined compsets or combinations are supported for each site and let users pick one.

I created an issue for it here: https://github.com/NorESMhub/ctsm-api/issues/5.

**Comment by huitang-earth** [comment]
@evalieungh Yes, We should turn off MOSART for new model versions. This was suggested by Dev when we discussed together in Helsinki. It is kept on my "to-do" list.
