### ISSUE TITLE
conda install on SAGA generate too many files

### ISSUE THREAD

**Issue by huitang-earth** [NorESMhub/NorESM_LandSites_Platform#17]
@annefou  We are trying to install conda environment for the model platform, but it generates too many number of files, which is beyond the 100,000 files limits. How to solve the problem?

**Comment by annefou** [comment]
I guess you try to install it in your HOME area. I would rather install it in a project area (the limit on the number of files is about 1 million if I remember correctly).

anther solution is to use singularity.

**Comment by huitang-earth** [comment]
Thanks @annefou. I am thinking in the same direction. Singularity or Docker container might work? Which way do you recommend?

**Comment by emiliano-gelati** [comment]
Closed as we moved to NREC
