### ISSUE TITLE
Better way to add the configuration changes (patching) to cime and ctsm for the platform 

### ISSUE THREAD

**Issue by huitang-earth** [NorESMhub/NorESM_LandSites_Platform#18]
Current implementation is to copy the configuration and namelist files changed directly to the corresponding folder after "manage externals". Several problems still exist:
(1) Maintain and update is still time consuming. It would be better to have a script to add individual xml entries needed (using information kept in xsl file) to the existing files rather than replacing the whole file.  
(2) Patching of CTSM and CIME will lead to changes in the corresponding local git repo of CTSM and CIME, the changes need to be commit in some way.
(3) How to re-do patching, if there have been existing patching?

**Comment by evalieungh** [comment]
Is this still an issue?
