### ISSUE TITLE
build documentation for the land site platform

### ISSUE THREAD

**Issue by huitang-earth** [NorESMhub/NorESM_LandSites_Platform#22]

**Comment by evalieungh** [comment]
We can use MkDocs. Quote Lasse from the Teams chat: " a solution that should be good for our purposes: MkDocs, which takes care of building a Read the Docs style github page with only a few lines of cli commands. The easiest way to maintain it is to include some necessary files in the main branch, specifically a "mkdocs.yml" file with simple instructions and then a "docs" directory containing the actual content of the page. Then, after executing a command, a new branch called "gh-pages" is automatically created with the necessary files for GitHub to build, render, and host the page. The site content can be managed via simple yet powerful Markdown files. IMO, it's a good compromise between easy to implement and maintainability."

**Comment by evalieungh** [comment]
Our documentation page is now up [here](https://noresmhub.github.io/NorESM_LandSites_Platform)
When updating the documentation, only these three files should be touched:
- docs/index.md (the technical documentation itself)
- docs/contributing.md (how to contribute to platform development and documentation)
- README.md (the repository's readme file is linked to become the About section on the page)
