### ISSUE TITLE
explore the possibility of using NREC for developing platform

### ISSUE THREAD

**Issue by huitang-earth** [NorESMhub/NorESM_LandSites_Platform#27]
Suggested by @annefou. Will check if NREC is available for model testing.

**Comment by emiliano-gelati** [comment]
Based on
- the [latest NREC VM setup](https://github.com/NorESMhub/NorESM_LandSites_Platform/tree/fix_config_dependencies/.machine/NREC_VM_setup), where key dependencies are compiled in [`install_dependencies.sh`](https://github.com/NorESMhub/NorESM_LandSites_Platform/blob/fix_config_dependencies/.machine/NREC_VM_setup/install_dependencies.sh), which is adapted adapted from the [CTSM Dockerfile](https://github.com/sunnivin/docker-local-build-run-CTSM/blob/1774e7aa6c49cfbe10dae18ceb7dc2739e099d7c/docker/baseos/centos/centos7.6/Dockerfile)
- [`config_compilers.xml`](https://github.com/NorESMhub/NorESM_LandSites_Platform/blob/fix_config_dependencies/config/cime/config_compilers.xml) and [`config_machines.xml`](https://github.com/NorESMhub/NorESM_LandSites_Platform/blob/fix_config_dependencies/config/cime/config_machines.xml), which are taken from the [`cime_config` to run CTSM with Docker](https://github.com/sunnivin/docker-local-build-run-CTSM/tree/1774e7aa6c49cfbe10dae18ceb7dc2739e099d7c/docker/ctsm/cime_config)

we could create, setup and build a case, but got an error when trying to run it. Log file attached: [cesm.log.210623-095846.txt](https://github.com/NorESMhub/NorESM_LandSites_Platform/files/6702346/cesm.log.210623-095846.txt)

**Comment by emiliano-gelati** [comment]
Solved by https://github.com/NorESMhub/NorESM_LandSites_Platform/pull/35
