### ISSUE TITLE
Set up development tools on NREC VM

### ISSUE THREAD

**Issue by emiliano-gelati** [NorESMhub/NorESM_LandSites_Platform#36]
Jupyter Lab: https://github.com/NorESMhub/NorESM_LandSites_Platform/commit/a9244bdaba341cb3e5ee36965f7233810ba54a0b#diff-5e5658a4a04ae29f5fa5af3dd675b769d9258e44d78a879ac336636b4b5f4eaf

**Comment by evalieungh** [comment]
OK to close this issue? NREC has been set up and is working as far as I know, and we can use Jupyter notebooks on Docker.
