### ISSUE TITLE
How to deal with history output setting for the platform

### ISSUE THREAD

**Issue by huitang-earth** [NorESMhub/NorESM_LandSites_Platform#39]
There are too many history output variables from CLM. It might not be practical to list all the variables for the user to choose. Instead, we may allow the model to output all the variables on hourly, daily or monthly scale, since the size of the output file is not a big issue. 

Or, we could group the output variables into several domains of interests, and people could chose which domain of variables are of their interests?

**Comment by evalieungh** [comment]
I've just gone through the long list of variables, and made a much shorter list of output variables that I think may be the most interesting for ecologists at least, but maybe others too. @lasseke suggested we can use such a list in the settings file and postprocessing script to make it easier for users. The list and scripts are not complete, though!

**Comment by evalieungh** [comment]
The shortened list is visible in [pull request 50](https://github.com/NorESMhub/NorESM_LandSites_Platform/pull/50), but this is a work in progress.
