### ISSUE TITLE
Improve installation scripts (🚧)

### ISSUE THREAD

**Issue by lasseke** [NorESMhub/NorESM_LandSites_Platform#46]
I just tried to set up all the platform dependencies on NREC from scratch for documentation purposes (_i.e., assuming all the Linux dependencies are properly installed and only considering platform-specific Python and NorESM dependencies including the `.cime` folder creation_) and realized that the various installation files we have make this process difficult to navigate. It would be nice to decouple these steps in a centralized `make` file or to update `install.sh` so that it first clones the correct NorESM version, then applies the patching, then takes care of the machine settings (via creating `.cime`), and then installs the `landsites_tools` and other Python dependencies in `setup.py` and `requirements.txt` (also, should we stick to pip or require conda?).

**Comment by emiliano-gelati** [comment]
Are you referring to the steps in https://github.com/NorESMhub/NorESM_LandSites_Platform/blob/platform_dev/.machine/NREC_VM_setup/setup_VM_NREC.sh ?

As for the Python package manager, I think we can keep using pip as we are root on virtual machines (the same will be when installing dependencies in a container), so conda is not necessary.

**Comment by lasseke** [comment]
Sorry for being unclear, I am mainly referring to some thematic overlaps in https://github.com/NorESMhub/NorESM_LandSites_Platform/blob/platform_dev/.machine/NREC_VM_setup/install_platform.sh and https://github.com/NorESMhub/NorESM_LandSites_Platform/blob/platform_dev/install.sh

Also thanks for your input on python dependencies, I will delete `environment.yml` and replace it with a `requirements.txt` in this case!

**Comment by emiliano-gelati** [comment]
Thanks @lasseke 

I think https://github.com/NorESMhub/NorESM_LandSites_Platform/blob/platform_dev/install.sh is obsolete, probably not working, and should be removed.

https://github.com/NorESMhub/NorESM_LandSites_Platform/blob/platform_dev/.machine/NREC_VM_setup/install_platform.sh is the one used for creating NREC virtual machines and is called by the [main script creating a VM from scratch](https://github.com/NorESMhub/NorESM_LandSites_Platform/blob/platform_dev/.machine/NREC_VM_setup/setup_VM_NREC.sh).

Perhaps we could expand the [script creating the VM from our base image](https://github.com/NorESMhub/NorESM_LandSites_Platform/blob/platform_dev/.machine/NREC_VM_setup/create_VM_latest_image.sh) by including the [missing step that clones CTSM and the platform](https://github.com/NorESMhub/NorESM_LandSites_Platform/blob/platform_dev/.machine/NREC_VM_setup/setup_VM_NREC.sh#L49). Is also missing a command to install the platform as python package (maybe I have overseen it)?

**Comment by lasseke** [comment]
Closing this outdated issue, refer to #55 for follow-up discussions.
