### ISSUE TITLE
SSH into NREC virtual machine using Ubuntu on Windows

### ISSUE THREAD

**Issue by evalieungh** [NorESMhub/NorESM_LandSites_Platform#54]
This took a while to figure out, so I'm posting an issue here with a solution in case anyone else bumps into the same problem. 

When trying to log in to my instance on NREC from Ubuntu on my windows pc, I ran into an error with the ssh key. 
The error went something like this:
`@@@@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @@@@
Permissions 0777 for '/mnt/c/Users/username/.ssh/mykey' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.`

Attempts at changing permissions with `chmod 600 .ssh/mykey` did not change anything (check with `ls -l .ssh/mykey`).

The problem was that ubuntu does not change permissions for files in windows directories. See here for more info: [](https://github.com/Microsoft/WSL/issues/81) , [](https://superuser.com/questions/1323645/unable-to-change-file-permissions-on-ubuntu-bash-for-windows-10)

The solution for me was to copy the key into my windows subsystem for linux (wsl) home folder, found with `cd ~`. There the chmod command will work. To copy the files, use e.g. 
`cd /mnt/c/Users/username
cp .ssh/mykey ~.ssh/`

Then you can move to the home folder and set the correct permissions with the chmod command. 
`cd ~
chmod 600 .ssh/mykey`

I also moved the public key and keystone_rc.sh file, though I'm not sure if was necessary. 

Thanks to @emiliano-gelati, @huitang-earth for helping me google the right questions! 

This issue has been solved and can be closed.

**Comment by emiliano-gelati** [comment]
Well done!
`keystone_rc.sh` should be in your home folder (`~`) and the public key in `~/.ssh/`, so you did the right thing.
