### ISSUE TITLE
should we add a code of conduct?

### ISSUE THREAD

**Issue by evalieungh** [NorESMhub/NorESM_LandSites_Platform#63]
Do we need a code of conduct for using and contributing to the platform? 

We could copy the one used for FATES (<https://github.com/NGEET/fates/blob/master/CODE_OF_CONDUCT.md>), or simply state in docs/contributing that we follow the same code of conduct as they do, or make our own document using the same template (<https://www.contributor-covenant.org/version/1/4/code-of-conduct/>) or something else. If so, I'm thinking it can be set up as another section on the [documentation page](https://noresmhub.github.io/NorESM_LandSites_Platform/)

What do you think, @huitang-earth @lasseke @emiliano-gelati @yelizy ?

**Comment by lasseke** [comment]
They repeatedly refer to the responsibilities the project maintainers have in the document. Even though this will probably never really matter in real life, I'd argue that we should first find a mid/long-term plan for the project before making such commitments in a code of conduct. But it would still also be okay for me to simply copy the statements (which I fully endorse 😊)

**Comment by emiliano-gelati** [comment]
I also agree with the statements in the FATES code of conduct. So OK for me to include an adapted version.

**Comment by evalieungh** [comment]
I agree we should maybe be careful with which responsibilities we take on, especially since we are all on temporary contracts. When I have time I could copy the FATES text and modify/shorten it a bit to suit us better for our first 'release'.

**Comment by evalieungh** [comment]
#66

**Comment by evalieungh** [comment]
the COC document is in the docs folder now, but missing from the yaml file so it's not visible yet. Will fix this in the next PR
