### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by evalieungh** [NorESMhub/NorESM_LandSites_Platform#65]
The links in our wiki are outdated. Should we remove them? Do we need the wiki at all now that we have the documentation page? 

This is what is there: https://github.com/NorESMhub/NorESM_LandSites_Platform/wiki/Useful-materials-for-developing-NLP

**Comment by huitang-earth** [comment]
If we follow CLM practice, wiki could be used for keeping some useful information, like meeting notes. I agree that we need to move this page to some other places (e.g., a place to keep all the planning files)

**Comment by evalieungh** [comment]
The home page of the wiki now points to the documentation page, so it looks less confusing for new people. I suggest we upload future presentations etc about the platform there, too. 
Closing this for now.
