### ISSUE TITLE
restart file creation for seedclim sites

### ISSUE THREAD

**Issue by huitang-earth** [NorESMhub/NorESM_LandSites_Platform#82]
I will go through the necessary steps to create proper restart files for simulations over the seedclim sites:

(1) thousands of years pre-industrial simulation
(2) historical simulation from pre-industry to present

**Comment by evalieungh** [comment]
When the new model versions are incorporated and new input data is ready, start running spin-up simulations and see when it stabilises

**Comment by evalieungh** [comment]
We have decided not to provide restart files for the first published version. Might be relevant to include for future releases.
