### ISSUE TITLE
set default simulations using standard calendar

### ISSUE THREAD

**Issue by huitang-earth** [NorESMhub/NorESM_LandSites_Platform#84]
At the moment, we use "noleap" calendar, but for realistic simulations, standard calendar with leap year should be adopted.

**Comment by huitang-earth** [comment]
@evalieungh, here is the solution for noleap caleandar:
You need to install "cftime". https://pypi.org/project/cftime/

The recent versions have support for "noleap" year.

**Comment by huitang-earth** [comment]
I am making new atmospheric forcing from other reanalysis data which have leap years. In that case, we will use "gregorian" calendar. This is something that should be in the documentation.

**Comment by evalieungh** [comment]
Great! Thanks for the link to cftime. 
Where do we specify the change to gregorian calendar? Is it a namelist parameter somewhere?

**Comment by evalieungh** [comment]
>   ./xmlchange --file env_build.xml --id CALENDAR --val GREGORIAN

changing this after a case has been built requires re-building the case.

**Comment by evalieungh** [comment]
Setting the calendar has been added to the GUI by @ka7eh. Closing this issue for now
