### ISSUE TITLE
update CTSM and FATES version, and document the workflow

### ISSUE THREAD

**Issue by huitang-earth** [NorESMhub/NorESM_LandSites_Platform#89]
Update noresm version to fetch the latest release of CTSM:
https://github.com/NorESMhub/NorESM/tree/noresm_landsites

The branch now have CTSM: release-clm5.0.35

The old version of NorESM that works with the current implementation of NLP is kept as a tag:
https://github.com/NorESMhub/NorESM/releases/tag/release-nlp0.1.0

The setup of NLP needs to be adapted with a pull request

**Comment by huitang-earth** [comment]
@lasseke Why "install.sh" is moved to "old_scripts"? We do need to install the platform some times to update the model version and docker image?

**Comment by huitang-earth** [comment]
@lasseke Do you use ".machine/NREC_VM_setup/install_platform.sh" to install the platform and download NorESM?

**Comment by huitang-earth** [comment]
what's the point of having "privileged" folder?
"https://github.com/NorESMhub/NorESM_LandSites_Platform/tree/platform_dev/.machine/NREC_VM_setup/privileged"

**Comment by huitang-earth** [comment]
I am confused whether I should update ".machine/NREC_VM_setup/install_platform.sh" or ".machine/NREC_VM_setup/privileged/install_platform_user.sh" or both?

**Comment by lasseke** [comment]
The `privileged/` folder was created by @MichalTorma as a cleaner way to install the platform dependencies within the Docker image. You can check the order in which these scripts are executed [in the Docker file](https://github.com/NorESMhub/NorESM_LandSites_Platform/blob/platform_dev/docker/Dockerfile). This should be the preferred method also for NREC to avoid having to maintain multiple files that do the same job.

We should clean/split up the installation folder and create one subfolder dedicated to the setup on NREC, where we should then call the updated scripts accordingly.

**Comment by lasseke** [comment]
while you are at it @huitang-earth, we purposely did not touch the installation steps for NorESM. There are still many out-commented lines in [install_platform_user.sh](https://github.com/NorESMhub/NorESM_LandSites_Platform/blob/platform_dev/.machine/NREC_VM_setup/privileged/install_platform_user.sh) and it is not easy to understand why the patching from the ESCOMP container is necessary or how it could be maintained for future versions. Please improve this when you touch the files!

**Comment by huitang-earth** [comment]
Thanks @lasseke  for the clarification. I will do the updates soon.

**Comment by huitang-earth** [comment]
Comment by Kaveh: "have you tested the platform with the external changes introduced here? https://github.com/NorESMhub/NorESM/commit/f1aaabd1d40526a8b00a0ca1bf576b0622a3ec61I was just testing and it looks broken. Looks like cime/src/components/data_comps_mct doesn't exist on `cime5.6.39`. I haven't gone further to see if there are other broken changes."
