### ISSUE TITLE
Several issues with running docker container

### ISSUE THREAD

**Issue by huitang-earth** [NorESMhub/NorESM_LandSites_Platform#95]
1. If running you are running jupyter notebook already, you will get the 

> error: 8888: bind: address already in use 

2. Do we need to remove or close the container after use, e.g.,   

> sudo docker-compose down
> sudo docker rm -f $(sudo docker ps -aq)

3. I need "sudo" in the container, which asks for password? What is the password for the root password in the container?
> sudo docker ps
> sudo docker container exec -u 0 -it c48485a94568 bash

**Comment by evalieungh** [comment]
The version in main branch right now points to a not-yet implemented address for the Docker image. This will give an error:

> ERROR: manifest unknown

Temporary fix is to open the docker-compose.yml file and replace the address (image: "ghcr.io/noresmhub/noresm_land_sites_platform:${VERSION:-latest}") with this one: ghcr.io/noresmhub/noresm_land_sites_platform:platform_dev

**Comment by evalieungh** [comment]
this should work now
