### ISSUE TITLE
add nco, cdo to requirements

### ISSUE THREAD

**Issue by evalieungh** [NorESMhub/NorESM_LandSites_Platform#96]
@huitang-earth @lasseke 

for quick manipulation of netcdf files.

**Comment by lasseke** [comment]
and `scipy`, required for running [FatesPFTIndexSwapper.py](https://github.com/NGEET/fates/blob/master/tools/FatesPFTIndexSwapper.py).

**Comment by evalieungh** [comment]
to quote Kaveh, ncdump comes with the default netcdf package on Ubuntu (on the api docker container), so it should be enough to just open a terminal to that container by typing this in the repo root: docker-compose exec api bash

**Comment by lasseke** [comment]
...and is now also included in the Jupyter environment! (localhost:8888, new terminal)
